### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by sekjun9878** [sourcerer-mike/phpsemver#24]
Hello,

Under what license is this project in? MIT?

**Comment by sourcerer-mike** [comment]
Thanks for that! Really.

I never thought about it because I didn't know licenses very well since now.
After reading some of them I like the MIT - very simple and everyone can do what he wants.
The next major version will have the MIT license.

**Comment by sourcerer-mike** [comment]
Done and will be in 3.0.0 !
Permanent checked / reminded via CodeSniffer from now on :)
